### ISSUE TITLE
Cant Generate data on premium content

### ISSUE THREAD

**Issue by phinneus1** [truedread/pyhulu#1]
when you try showtime/hbo/starz on demand content it results in 

Response:
*Video expired

any possibility to get around this?

**Comment by ghost** [comment]
This should be fixed by #2.

**Comment by jiujitsu** [comment]
@nyuszika7h hrm I tried your fix, but I get this error:

`client.load_playlist('EAB::f92568f9-b36d-4e21-969d-61de4050c633::61459960::75665312')`

```
Error decoding response hex
Request:
{
    "device_identifier": "D41D8CD98F00B204E9800998ECF8427E",
    "deejay_device_id": 159,
    "version": 1,
    "content_eab_id": "EAB::f92568f9-b36d-4e21-969d-61de4050c633::61459960::75665312",
    "rv": 255281,
    "kv": 18239
}
Response:
{"code":"BYA-403-020","hci_code":"hulu:playstack:error:bya-403-020","message":"Invalid token [user]: REVOKED_USER"}
```

And then even on non showtime/hbo I still get the same error. Example eab: `00d22774-929e-4385-847f-2b3183e4a657`

Any ideas?
